apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-6
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-test-6
    app.kubernetes.io/part-of: test-application
  name: multi-6
  namespace: default
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: multi-6
status:
  loadBalancer: {}
