apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-62
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-test-62
    app.kubernetes.io/part-of: test-application
  name: multi-62
  namespace: default
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: multi-62
    weight: 100
status: {}
